services:
  expo-app:
    build: .
    ports:
      - "8081:8081"
      - "19000:19000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"